# Generated by Django 3.2.3 on 2022-05-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doljnost',
            fields=[
                ('id', models.IntegerField(db_index=True, help_text='Уникальный индификатор', primary_key=True, serialize=False)),
                ('name_doljnost', models.CharField(help_text='Введите должность работника ', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Facultet',
            fields=[
                ('id', models.IntegerField(db_index=True, help_text='Уникальный индификатор', primary_key=True, serialize=False)),
                ('name_faculteta', models.CharField(help_text='Введите абривиатуру (название) факультета ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Forma_kontrol9',
            fields=[
                ('id', models.IntegerField(db_index=True, help_text='Уникальный индификатор', primary_key=True, serialize=False)),
                ('vid_formi', models.CharField(help_text='Введите вид занятия (Например лекция, практическое занятие, лабараторное) ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(db_index=True, help_text='Уникальный индификатор', primary_key=True, serialize=False)),
                ('name_group', models.CharField(help_text='Введите номер (название) группы ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Napravlenie',
            fields=[
                ('id', models.IntegerField(db_index=True, help_text='Уникальный индификатор', primary_key=True, serialize=False)),
                ('name_napravlenie', models.CharField(help_text='Введите номер (название) направления ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.IntegerField(db_index=True, help_text='Уникальный индификатор', primary_key=True, serialize=False)),
                ('name_premeta', models.CharField(help_text='Введите название предмета', max_length=70)),
                ('id_forma_kontrol9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.forma_kontrol9')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
