# Generated by Django 3.2.3 on 2022-05-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220515_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('id_facultet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.facultet')),
                ('id_groupa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.group')),
                ('id_napravlenie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.napravlenie')),
            ],
        ),
    ]
