# Generated by Django 3.2.3 on 2022-05-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_studenti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kolvo_propyskov', models.IntegerField(help_text='Количество пропусков')),
                ('id_predmeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.predmet')),
                ('id_rabotnika', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.rabotnik')),
                ('id_studentov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.studenti')),
            ],
        ),
    ]
