# Generated by Django 3.2.3 on 2022-05-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20220515_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurnal',
            name='kolvo_propyskov',
        ),
        migrations.AddField(
            model_name='jurnal',
            name='data_propyskov',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='propyski',
            field=models.BooleanField(default=True, help_text='Присутсвовал/Отсутсвовал'),
        ),
    ]
