# Generated by Django 3.2.3 on 2022-05-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_jurnal_opisanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnal',
            name='opisanie',
            field=models.TextField(blank=True, help_text='Описание', max_length=1000, null=True),
        ),
    ]
