# Generated by Django 3.2.3 on 2022-05-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_jurnal_opisanie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predmet',
            old_name='name_premeta',
            new_name='name_predmeta',
        ),
    ]
