# Generated by Django 3.2.3 on 2022-05-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_name_premeta_predmet_name_predmeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenti',
            name='id_facultet',
        ),
        migrations.RemoveField(
            model_name='studenti',
            name='id_napravlenie',
        ),
        migrations.AddField(
            model_name='group',
            name='id_napravlenie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.napravlenie'),
        ),
        migrations.AddField(
            model_name='napravlenie',
            name='id_facultet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.facultet'),
        ),
    ]
