# Generated by Django 3.2.3 on 2022-05-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20220518_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabotnik',
            name='id_doljnost',
        ),
        migrations.DeleteModel(
            name='Doljnost',
        ),
    ]
