# Generated by Django 3.2.3 on 2022-05-21 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20220521_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name_group', '-id_napravlenie']},
        ),
        migrations.CreateModel(
            name='Rabotnik_Predmet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_predmet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.predmet')),
                ('id_rabotnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.rabotnik')),
            ],
        ),
    ]
