# Generated by Django 3.2.3 on 2022-05-21 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20220522_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurnal',
            name='id_predmeta',
        ),
        migrations.RemoveField(
            model_name='jurnal',
            name='id_rabotnika',
        ),
        migrations.AddField(
            model_name='jurnal',
            name='id_rabotnik_predmet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.rabotnik_predmet'),
        ),
    ]
