# Generated by Django 3.2.3 on 2022-05-21 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20220522_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurnal',
            name='id_rabotnik_predmet',
        ),
        migrations.AddField(
            model_name='jurnal',
            name='id_predmeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.predmet'),
        ),
        migrations.AddField(
            model_name='jurnal',
            name='id_rabotnika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.rabotnik'),
        ),
        migrations.DeleteModel(
            name='Rabotnik_Predmet',
        ),
    ]
