# Generated by Django 3.2.3 on 2022-05-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20220522_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id_napravlenie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.napravlenie'),
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='id_predmeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.predmet'),
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='id_rabotnika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.rabotnik'),
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='id_studentov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.studenti'),
        ),
        migrations.AlterField(
            model_name='napravlenie',
            name='id_facultet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.facultet'),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='id_forma_kontrol9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.forma_kontrol9'),
        ),
        migrations.AlterField(
            model_name='rabotnik',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rabotnik',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rabotnik',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studenti',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studenti',
            name='id_groupa',
            field=models.ForeignKey(default=125, on_delete=django.db.models.deletion.PROTECT, to='catalog.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studenti',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studenti',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
