# Generated by Django 3.2.3 on 2022-06-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20220530_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficsation',
            name='propyski',
            field=models.BinaryField(default=0, help_text='Присутсвовал/Отсутсвовал'),
        ),
    ]
