# Generated by Django 3.2.3 on 2022-06-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_ficsation_id_nomer_zapisi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficsation',
            options={'ordering': ['data_propyskov']},
        ),
    ]
