# Generated by Django 3.2.3 on 2022-06-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_ficsation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenti',
            options={'ordering': ['-id_groupa', '-last_name']},
        ),
    ]
