# Generated by Django 3.2.3 on 2022-06-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_studenti_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurnal',
            options={'ordering': ['id_studentov']},
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='id_studentov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.studenti'),
        ),
    ]
